### PR TITLE
Backport of JGRP-2234

### PR DESCRIPTION
**Pull request by lennon-niall**

### CODE REVIEW

**Comment by belaban** [comment]
LockServiceConcurrenyTest fails:
==> received GRANT_LOCK request #1

java.lang.AssertionError: the lock acquisition should have failed

	at org.jgroups.tests.LockServiceConcurrencyTest.testConcurrentClientLocks(LockServiceConcurrencyTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by belaban** [comment]
This still fails for me 2 out of 3 times, whereas it doesn't on master (4.x branch)... I fail to see why dropping the timeout from 10 to 4 ms would fix this

**Comment by lennon-niall** [comment]
Thanks for the reply Bela Ban, Id like to confirm the contents of the backport for this fix (JGRP-2234) if thats ok.

So far Ive only included the following in my pull request to be dropped back:

6787fb71e592d041a0cd72c85e4930e31cf5adfc
Author: Bela Ban <belaban@yahoo.com>
Date:   Thu Feb 8 18:57:18 2018 +0100

    - Releasing a lock is now synchronous, similar to acquiring a lock
    - Release lock requests are resent on a view change
    - Added unit test for https://issues.jboss.org/browse/JGRP-2234


I've since found a two other changes which relate to JGRP-2234:

git log --grep=2234
commit 65a8e07bd752728f0578e4177d23406d42c480e6
Author: Bela Ban <belaban@yahoo.com>
Date:   Thu Feb 15 12:01:45 2018 +0100

    - Impl of CENTRAL_LOCK2 [https://issues.jboss.org/browse/JGRP-2249]
    - Design document: ./doc/design/CENTRAL_LOCK2.txt
    - Parameterized LockServiceTest (CENTRAL_LOCK, CENTRAL_LOCK2)
    - LockService_JGRP-2234_Test now tests both CENTRAL_LOCK and CENTRAL_LOCK2
    - LockServiceConcurrencyTest new tests both CENTRAL_LOCK and CENTRAL_LOCK2
    - ClusterSplitLockTest and RpcLockingTest now test both CENTRAL_LOCK and CENTRAL_LOCK2
    - Added req-queue and req-handler (started on becoming coord)
    - Updated manual


commit b924fdbd9f237d53d2561e8b431c3b836e888fd3
Author: Bela Ban <belaban@yahoo.com>
Date:   Mon Feb 5 17:28:43 2018 +0100

    Fixed wong keyserver in ASYM_ENCRYPT (https://issues.jboss.org/browse/JGRP-2234)


Should I include both of the above in my pull request also?

**Comment by belaban** [comment]
@lennon-niall I'm afraid I don't have time to look into this, but if you can come up with a PR that (1) makes the 2 lock tests pass and (2) is as small as possible, only changing lock-related classes and not other critical core classes, then I'm all in.

**Comment by lennon-niall** [comment]
Hi Belaban, LockServiceConcurrencyTest now passing with the updates below which align with master (4.x branch):

1) Change to use Locking class instead of Protocol base class
2) DropGrantResponse class updated to override the correct methods.

https://github.com/belaban/JGroups/pull/418/commits/743635fa7f1d000eb5fa680739748ba23c44b0d9

**Comment by belaban** [comment]
When 3.6.18 has gatherered a few JIRAs.

**Pull request merged**
