### PR TITLE
JGRP-1930 RELAY2: SiteUUID and regular UUID are bundled by TransferQu…

### PR DESCRIPTION
**Pull request by pruivo**
…eueBundler

* Make sure that the SingletonAddress makes the distinction between SiteUUID and UUID.

https://issues.jboss.org/browse/JGRP-1930

note: I had to change the SingletonAddress. I couldn't change the compareTo from SiteUUID and UUID to return always different because jgroups was unable to find the physical address.

### CODE REVIEW

**Comment by belaban** [comment]
Did you verify that the change in {{SiteUUID.compareTo()}} doesn't have any negative effect in {{RELAY2}}/{{Relayer}} ?

**Comment by pruivo** [comment]
your tests were green for me. when I first tried to a more aggressive ```compareTo``` (i.e.e returning ```!= 0``` when the we compare different ```Address``` classes) I got some failures and some "no physical address found" errors.

so, I'm pretty sure that it is fine :)

**Comment by belaban** [comment]
OK. Make sure to run the xsite testsuite in Infinispan as well with the changes, to see if this works.
Cheers,thx,

**Comment by pruivo** [comment]
infinispan x-site test suite is OK.

**Comment by belaban** [comment]
Great, thx.
I'm closing the JIRA issue now

**Pull request merged**
