### PR TITLE
JGRP-2647 NioServer does not ensure closure of its server channel on stop

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/JGRP-2647

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
Looks good to me (also I want to whip up a quick test to verify this fixes our problem as that could be potentially fairly straightforward).

**Comment by belaban** [comment]
This is the code I use:
{code,java}
     if(running.compareAndSet(true, false)) {
            // Util.close(selector); // closing the selector also stops the acceptor thread
            // socket_factory.close(channel);
            selector.wakeup();
            // Wait for server channel to close (via acceptorDone())
            Util.interruptAndWaitToDie(acceptor);
        }
{code}

**Comment by rhusar** [comment]
@belaban That looks fine. I have updated https://github.com/belaban/JGroups/pull/672 accordingly.

**Comment by pferraro** [comment]
Thanks @belaban.  Global.THREAD_SHUTDOWN_WAIT_TIME makes much more sense. :)
Can we get a 5.2.8 soon with this change?  We had to temporarily revert back to FD_SOCK due to this.

**Comment by belaban** [comment]
Hi @pferraro I hope to release this week

**Pull request closed without merging**
