### PR TITLE
JGRP-2286 VERIFY_SUSPECT can return false positives if member is killed and immediately restarted

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/JGRP-2286

### CODE REVIEW

**Comment by pferraro** [comment]
@belaban Please review.

**Comment by danberindei** [comment]
@belaban @pferraro I'm not sure this fixes anything... the logs attached in https://issues.jboss.org/browse/ISPN-9517 show that the old node is removed from the view just fine

**Comment by pferraro** [comment]
@danberindei is right. So long as VERIFY_SUSPECT sends ARE_YOU_DEAD messages as unicasts, they should be ignored by the transport of the reincarnated member via TP.unicastDestMismatch(...)  @belaban You can revert this.

**Comment by belaban** [comment]
Reverted

**Comment by belaban** [comment]
Hmm, this is not true:
`public boolean unicastDestMismatch(Address dest) {
        return dest != null && !(Objects.equals(dest, local_addr) || Objects.equals(dest, local_physical_addr));
    }`

If dest != local_addr, but dest == local_physical_addr, then the message would _not_ get discarded... not sure why I once added the second part of the condition...

**Comment by pferraro** [comment]
@belaban Would that mean this still be an issue when use_ip_addrs is enabled?

**Comment by danberindei** [comment]
@belaban could it be because some protocols (maybe discovery?) need to send messages to a particular physical address? I would expect this kind of usage to be quite limited though, and the protocols that use physical addresses should have some kind of protection against reincarnation themselves.

OTOH I'm not sure `VERIFY_SUSPECT.use_icmp` could ever work... any time the JVM crashes but the machine stays up, the node is not going to be removed from the view. If another node is started on the same machine, it won't remove the old node from the view either.

**Comment by belaban** [comment]
@danberindei Yes, you're right: TCPPING needs to send messages to physical addresses when iterating through `initial_hosts`

**Comment by belaban** [comment]
OK @pferraro Have you come up with a reproducer?
So the current logic does _not_ discard a message if the UUID is the same as the local address OR the destination is a physical address and the local physical address is the same. This means reincarnation is possible *if* the destination is a physical address and it equals the local physical address.
However, this should *only* be possible in TCPPING. That's the only case where we ever send physical addresses rather than UUIDs in a message.

**Pull request merged**
