### PR TITLE
JGRP-2370 JGRP-2371 SSL_KEY_EXCHANGE Elytron integrationability fixes

### PR DESCRIPTION
**Pull request by rhusar**
Jiras
https://issues.jboss.org/browse/JGRP-2370
https://issues.jboss.org/browse/JGRP-2371

Blocks
https://issues.jboss.org/browse/WFLY-12164

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro Would you mind reviewing?

**Comment by belaban** [comment]
@rhusar Looks god to me. Do you still want to wait for Paul's review?

**Comment by rhusar** [comment]
@belaban Just please, just discussing.

**Comment by pferraro** [comment]
:+1:

**Comment by belaban** [comment]
merged

**Pull request merged**
