### PR TITLE
Fix Relay2Header toString() format

### PR DESCRIPTION
**Pull request by pruivo**

### CODE REVIEW

**Review by belaban — COMMENTED** [review]
Hmm, I dont like the change, as I do *not* want to show sites or visited_sites when they're null or empty. Besides, I changed this in the JGRP-2706 branch already

**Comment by pruivo** [comment]
why is that?

**Comment by belaban** [comment]
Only show essential stuff, to not confuse the user

**Comment by belaban** [comment]
Wait for my fix in 2706! Cheers :-)

**Pull request closed without merging**
