### PR TITLE
Add explicit module info

### PR DESCRIPTION
**Pull request by bowbahdoe**
Adds an explicit module-info to the final artifact

### CODE REVIEW

**Comment by belaban** [comment]
Hmm... compilation with ant and mavcen succeeds, but IntelliJ complains:
java: module not found: org.apache.logging.log4j.core
java: module not found: org.apache.logging.log4j
java: module not found: org.slf4j

**Comment by bowbahdoe** [comment]
This is perhaps not helpful, but IntelliJ is working fine on my machine. Maybe you need to upgrade your IJ?

**Comment by belaban** [comment]
Still the same problem, I'm on 2023.2.6

**Comment by bowbahdoe** [comment]
Thats the same version as me. 

I nuked my local and re-cloned from github and all was fine. Maybe its an issue as to whether its a "maven project" in intellij's eyes? I'm also on a mac if that ends up mattering.

(I definitely have incentive to figure out whats going on - partially so you don't revert and partially so I can be aware of this in the future)

**Comment by tristantarrant** [comment]
I think that this pr must have a few tests executed with the modular path,
otherwise it's hard to validate its correctness.

Tristan

**Comment by belaban** [comment]
This is driving me crazy and now I have a new error: Exception in thread "main" java.lang.NoClassDefFoundError: production/JGroups/module-info is not a class because access_flag ACC_MODULE is set.

Same issue regardless whether I import the project as maven or from srcs (ant).

I'm removing `module-info.java`, as it prevents me from working. I'll leave the changes in `build.xml` and `pom.xml`.

**Pull request merged**
