### PR TITLE
JGRP-2243 provided the INJECT_VIEW protocol to inject arbitrary views in nodes.

### PR DESCRIPTION
**Pull request by valdar**

### CODE REVIEW

**Comment by valdar** [comment]
https://issues.jboss.org/browse/JGRP-2243

Comments/Suggestions are welcome.

**Comment by belaban** [comment]
Thanks Andrea! I pushed the changes to upstream, plus updated the docu on the website.

**Comment by belaban** [comment]
Oops, this doesn't work: `probe.sh op=INJECT_VIEW.injectView["A=A;B=B,C;C=B,C"]`!

JGroups tries to parse the arguments as a comma-separated list and therefore gets the following arguments: `A=A;B=B`, `C;C=B` and `C`...

The simplest solution would be to change the NAMES_SEPARATOR from `,` to something else. wdyt?

**Comment by valdar** [comment]
Sure, should be a trivial change; I'm on it!

**Comment by valdar** [comment]
new PR: https://github.com/belaban/JGroups/pull/376

**Pull request merged**
