### PR TITLE
JGRP-2811 Support time units parsing for property values

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/JGRP-2811

### CODE REVIEW

**Comment by belaban** [comment]
`probe` fails: `probe.sh MERGE3.min_interval="25s"`; I'll fix this

**Comment by belaban** [comment]
OK, I made some changes and the testsuite passes. Thanks for the contribution, @tristantarrant ! Do you want me to backport this to the 5.3.x branch?

**Comment by tristantarrant** [comment]
Not strictly necessary. When are you planning on releasing 5.4 ?

**Comment by belaban** [comment]
5.4 will take some time, I'm working on `NAKACK3` and `NAKACK4`... I'll backport to 5.3.x then, which I'll release in a few weeks

**Comment by belaban** [comment]
and backported... I have issues logging into JIRA, to add 5.3.8 as fix-release, will retry tomorrow.

**Pull request closed without merging**
