### PR TITLE
[master] JGRP-2153 Encrypt protocols transform empty buffer into null buffer when encrypt_entire_message is disabled

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/JGRP-2153

### CODE REVIEW

**Comment by belaban** [comment]
Paul, I don't think this will work if the buffer is null!
How about just setting the buffer to "" if it is it's size is 0 or it is null?

**Comment by belaban** [comment]
Not sure I like this fix: we'll encrypt null or empty messages and also have to decrypt them. This is additional work, that would not be needed if your Marshaller was able to handle null buffers...

**Comment by pferraro** [comment]
When is the buffer ever null?  Remember, a null RPC response does not translate to a null buffer.

**Comment by pferraro** [comment]
I disagree, this is a matter of symmetry.  If a sender encrypts and sends an empty buffer, the receiver should receive and decrypt the message as an empty buffer - not a null buffer.

**Comment by belaban** [comment]
If the buffer is never null, why do we get NPEs on the de-serialization?

**Comment by belaban** [comment]
I agree on the symmetry argument

**Comment by belaban** [comment]
Paul, you're not the only one sending messages down a channel. So if an app happens to use a different Marshaller, or an app uses the JChannel directly to send a message with a null buffer, we'll get an exception trying to encrypt the message!

**Comment by pferraro** [comment]
Surely it is always up to the Marshaller to be able to unmarshal any buffer that it marshalled.  I don't think we should expect a Marshaller to be able to unmarshal a value that it never marshalled!

Anyway - I'll modify this commit to additionally handle null buffers.

**Comment by pferraro** [comment]
Actually, I like the idea of bypassing encrypt/decrypt for empty buffers.  I'll modify.

**Comment by pferraro** [comment]
"If the buffer is never null, why do we get NPEs on the de-serialization?"
Because the encrypt protocol converts what was an empty buffer into a null buffer.  This is the crux of the problem.

**Comment by belaban** [comment]
I think the PR will cause problems returning a null encrypted message: when sign_msg is true, this will cause an NPE.
OK, so I think I'll do the following:
* When a buffer is null -> don't encrypt a message and pass it down. On the receiver side, a null buffer is not decrypted and passed up as well (assuming encrypt_entire_message is false in both cases)
* When the buffer is empty -> don't encrypt and pass down, same on the receiver side
* Otherwise enrypt when sending and decrypt when receiving

**Comment by pferraro** [comment]
OK - feel free to close this.

**Comment by pferraro** [comment]
Hang on a sec - I don't see how this PR would cause any new NPEs.  It looks like this protocol was not implemented with null buffers in mind.  All of the encrypt_entire_message and sign_msg logic assumes a non-null buffer.
Bela, are you sure that a null buffer is even a valid use case in JGroups?  Would we even be talking about this if the *_ENCRYPT protocols weren't erroneously creating a null buffer from an empty one?

**Comment by belaban** [comment]
Yes, null buffers are a valid use case; e.g. some app sending a message with a application-defined header and a null buffer.
You're right, creating a null message from an empty (non-null) buffer wreaks havoc, and my suggestion in my previous comment will fix this.

**Comment by pferraro** [comment]
OK - sounds like we're on the same page.  I'll close this and eagerly await your fix. :)

**Comment by belaban** [comment]
OK. Just don't be too eager, I have other stuff on my plate... :-)

**Pull request closed without merging**
