### PR TITLE
S3 ping2 rc1

### PR DESCRIPTION
**Pull request by TarantulaTechnology**
**AWS Authentication Version 4 Support for JGroups**
Copied S3_PING and modified it to support Amazon AWS Authentication Version 4 RESTful API. 

- Added protocol ID.
- Placed code in packages to isolate from existing codebase. 
- Added several JUnit tests to exercise the new code. 
- Provided JUnit tests to learn how to use the new functionality. 
- Added udp-s3_ping2.xml, which contains the minimum configuration parameters for S3_PING2. 
- Any AWS region can be accessed by setting the configuration parameter "region". 
- The code was also tested with the demo Draw, successfully accessing the Frankfurt region by setting Draw -props to s3_ping2.xml. 
The functionality is complete, but not optimized, and code is verbose, rather than concise, as a result of the initial effort which was focused on getting the functionality in place, working, and cause minimal disruption to existing code.
- Future efforts will focus on optimizing and consolidating redundant code and collapsing common code creating a smaller and tighter codebase.

Mark Morris
July 6, 2016

### CODE REVIEW

**Comment by belaban** [comment]
Hmm, 168K? Really? ... :-)
* AWS_AUTH4Test fails.
* I'm thinking the better place for S3_PING2 would be http://www.github.com/jgroups-extras. There, you would have complete control of the code, plus you could add dependencies, making your code smaller... wdyt?

**Comment by TarantulaTechnology** [comment]
Sounds good.

**Comment by belaban** [comment]
OK. Send me your Github user name and I'll add you to jgroups-extras.
Cheers,

**Comment by TarantulaTechnology** [comment]
TarantulaTechnology

**Comment by belaban** [comment]
Sent you an invite. You should be able to create a new repo now.

**Comment by TarantulaTechnology** [comment]
Thx Bela.

**Pull request closed without merging**
