### PR TITLE
Replace org.testng.annotations.Test#parallel with org.testng.annotati…

### PR DESCRIPTION
**Pull request by rhusar**
…ons.Test#singleThreaded

This should do the trick for the new TestNG

### CODE REVIEW

**Comment by rhusar** [comment]
As per javadoc https://javadoc.io/doc/org.testng/testng/6.9.4/org/testng/annotations/Test.html

**Comment by belaban** [comment]
Thanks, Rado!

**Comment by belaban** [comment]
Also removed singleThreaded=false expression (redundant)

**Comment by rhusar** [comment]
Makes sense.

**Pull request merged**
