### PR TITLE
JGRP-2631 Multi-Release JAR

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/JGRP-2631

### CODE REVIEW

**Comment by rhusar** [comment]
I have added JDK 19 to the test matrix - https://github.com/belaban/JGroups/pull/651 - can you just rebase and push your branch? (Unfortunately that's how GH Actions work).

**Comment by tristantarrant** [comment]
Looking at the JDK 19 build, everything is ok:
```
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ jgroups ---
[INFO] Compiling 464 source files to /home/runner/work/JGroups/JGroups/target/classes
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/protocols/Locking.java: Some input files use or override a deprecated API.
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/protocols/Locking.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/util/SecurityActions.java: Some input files use or override a deprecated API that is marked for removal.
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/util/SecurityActions.java: Recompile with -Xlint:removal for details.
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/stack/Protocol.java: Some input files use unchecked or unsafe operations.
[INFO] /home/runner/work/JGroups/JGroups/src/org/jgroups/stack/Protocol.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (jdk-19) @ jgroups ---
[INFO] Compiling 1 source file to /home/runner/work/JGroups/JGroups/target/classes/META-INF/versions/19
[INFO] /home/runner/work/JGroups/JGroups/mr/19/src/org/jgroups/util/jdkspecific/ThreadCreator.java: /home/runner/work/JGroups/JGroups/mr/19/src/org/jgroups/util/jdkspecific/ThreadCreator.java uses preview features of Java SE 19.
[INFO] /home/runner/work/JGroups/JGroups/mr/19/src/org/jgroups/util/jdkspecific/ThreadCreator.java: Recompile with -Xlint:preview for details.
```

I guess the release should be done with JDK 19 in order to have the bits in.

**Comment by tristantarrant** [comment]
@belaban do you want me to change the source directory for JDK 19 ?

**Comment by tristantarrant** [comment]
Also, the logs should probably be i18n'ized

**Comment by belaban** [comment]
No, it's fine. I'm changing build.xml, as it doesn't currently include the mr classes (the POM works fine)

**Comment by tristantarrant** [comment]
Note: it is always better to use `-release` instead of `-source/-target` because it ensures that API signature compatibility is maintained.

**Pull request merged**
