### PR TITLE
Release JGroups avoiding stagig repo

### PR DESCRIPTION
**Pull request by slaskawi**
Hey @belaban !

Recently I've been looking at different ways to release without staging repo. Luckily, this problem has been solved by Hawkular project [1]. 

Maybe it's worth trying this approach before customizing repositories at JBoss Nexus?

Thanks
Sebastian

[1] https://issues.jboss.org/browse/HAWKULAR-199 and implementation [2][3]
[2] https://github.com/hawkular/hawkular-build-tools/commit/b48133af85de156f3f7e14a68cab48704d81cb16
[3] https://github.com/hawkular/hawkular-build-tools/commit/bfe907f31ed4c4afbe9a6745303d48feda2a60f9

### CODE REVIEW

**Comment by belaban** [comment]
Hi @slaskawi, I applied the PR. Do I invoke it using `mvn deploy` ? That doesn't work, e.g.
````
mvn -Dmaven.test.skip=true deploy
...
main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:bundle (default-bundle) @ jgroups ---
[WARNING] Bundle org.jgroups:jgroups:bundle:3.6.4 : Instructions in Export-Package that are never used: schema
Classpath: Jar:.,Jar:log4j-core,Jar:log4j-api,Jar:tools

[WARNING] Bundle org.jgroups:jgroups:bundle:3.6.4 : Superfluous export-package instructions: [schema]
[WARNING] Bundle org.jgroups:jgroups:bundle:3.6.4 : Invalid value for Bundle-RequiredExecutionEnvironment, J2SE-1.6 does not match CDC-1\.0/Foundation-1\.0|CDC-1\.1/Foundation-1\.1|OSGi/Minimum-1\.[1-9]|JRE-1\.1|J2SE-1\.2|J2SE-1\.3|J2SE-1\.4|J2SE-1\.5|JavaSE-1\.6|JavaSE-1\.7|PersonalJava-1\.1|PersonalJava-1\.2|CDC-1\.0/PersonalBasis-1\.0|CDC-1\.0/PersonalJava-1\.0
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar-no-fork (attach-sources) @ jgroups ---
[INFO] Building jar: /Users/bela/JGroups/target/jgroups-3.6.4-sources.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jgroups ---
[INFO] Installing /Users/bela/JGroups/target/jgroups-3.6.4.jar to /home/bela/.m2/jboss-repository/org/jgroups/jgroups/3.6.4/jgroups-3.6.4.jar
[INFO] Installing /Users/bela/JGroups/pom.xml to /home/bela/.m2/jboss-repository/org/jgroups/jgroups/3.6.4/jgroups-3.6.4.pom
[INFO] Installing /Users/bela/JGroups/target/jgroups-3.6.4-sources.jar to /home/bela/.m2/jboss-repository/org/jgroups/jgroups/3.6.4/jgroups-3.6.4-sources.jar
[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:install (default-install) @ jgroups ---
[INFO] Installing org/jgroups/jgroups/3.6.4/jgroups-3.6.4.jar
[INFO] Writing OBR metadata
[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:deploy (default-deploy) @ jgroups ---
[INFO] Remote OBR update disabled (enable with -DremoteOBR)
[INFO] 
[INFO] --- nexus-staging-maven-plugin:1.6.5:deploy (injected-nexus-deploy) @ jgroups ---
[INFO] Performing local staging (local stagingDirectory="/Users/bela/JGroups/target/nexus-staging/staging")...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.335 s
[INFO] Finished at: 2015-06-15T16:06:53+01:00
[INFO] Final Memory: 38M/635M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy (injected-nexus-deploy) on project jgroups: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy failed: Mandatory plugin parameter 'nexusUrl' should be your Nexus base URL only - for example http://localhost:8081/nexus -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[mac] /Users/bela/JGroups$ 
````

**Comment by belaban** [comment]
Also, this is similar to `bin/release_to_nexus.sh`. With this, do I still have to open the Nexus GUI to release ?

**Comment by belaban** [comment]
The command below works, but I cannot find the uploaded artifact anywhere...
```
mvn deploy -Dmaven.test.skip=true  -DnexusUrl=https://repository.jboss.org/nexus/service/local/staging/deploy/maven2/ -DserverId=jboss-releases-repository -DskipLocalStaging=true

```

**Comment by belaban** [comment]
Only this is needed
```
mvn deploy -Dmaven.test.skip=true -DskipLocalStaging=true
```

**Comment by slaskawi** [comment]
Hey @belaban !

Actually it should work even without `-DskipLocalStaging=true`. You should be able to publish the artifacts using `mvn deploy -Dmaven.test.skip=true`.

**Comment by belaban** [comment]
I'm working on getting this to work in ant&ivy

**Pull request merged**
