### PR TITLE
JGRP-2614 Non-blocking API for counters

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/JGRP-2614

### CODE REVIEW

**Comment by rhusar** [comment]
@pruivo We should have a Jira for this to show up in release notes.

**Comment by belaban** [comment]
@pruivo: you by default implement `get()` as `addAndGet(0)`. Are you sure this is not causing a round-trip to the coordinator, rather than just a local read?

**Comment by belaban** [comment]
I'm adding a unit test

**Comment by pruivo** [comment]
@belaban wondering who wrote that :) 
https://github.com/belaban/JGroups/blob/303bb17254a0d3edddfd7f163316e5e7e9677356/src/org/jgroups/protocols/COUNTER.java#L635-L637

I'll update the PR tomorrow (or this evening)

**Comment by belaban** [comment]
Oh shit, terrible! :-) Yes, please fix it

**Comment by belaban** [comment]
One more issue: on a change (e.g. `incrementAndGet()`), the async API does not update the local counter, so the local counter (stored in hashmap `counters`) looks stale. (Of course, this doesn't happen on the coord). On the next `get()`, the value is updated correctly.

I have to confess that I'm fighting with debugging the async code; I'm not so sure it's a good idea to rewrite the entire `COUNTER` protocol in an async manner...

**Comment by pruivo** [comment]
That's weird and if it is not happening, then it is a bug somewhere.
`sendRequestToCoordinator()` invokes `updateCounter()` when it receives the reply from the coordinator.
Which test are you running?

**Comment by belaban** [comment]
I think `updateCounter()` *is* called, but it has the same version as the updatee, so the new value is not updated...

**Comment by belaban** [comment]
I applied your PR; we can open new PRs/JIRAs for issues found... cheers

**Comment by pruivo** [comment]
thanks @belaban

**Pull request merged**
