### PR TITLE
 Backport JGRP-2350 and JGRP-2354 to 4.0.20

### PR DESCRIPTION
**Pull request by danberindei**

### CODE REVIEW

**Comment by belaban** [comment]
Applied - running the test suite now and will release 4.0.20.Final as soon as it passes

**Comment by danberindei** [comment]
@belaban thanks, and sorry for opening #427 against master!

**Comment by belaban** [comment]
No problem

**Comment by belaban** [comment]
Oops, compilation errors... I'll fix them to run the testsuite

**Comment by belaban** [comment]
OK, testsuite passed 100%. Tagged as JGroups-4.0.20.Final and uploaded to mvn

**Pull request merged**
