### PR TITLE
[3.6] JGRP-2035 Revert "pmd:UseProperClassLoader - Use Proper Class Loader"

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/JGRP-2035

We'll need a 3.6.9.Final release containing this fix ASAP.

### CODE REVIEW

**Comment by belaban** [comment]
Thanks for catching this, Paul! This happened because of a stupid commit by a 'code cleaner'...

**Comment by pferraro** [comment]
Ah - that guy is from DevFactory: https://github.com/m-ezzat
I got a email this week from someone from DevFactory about doing similar tool-based code cleanup for HA-JDBC.  I'll make sure to closely scrutinize any PRs they propose.

**Comment by belaban** [comment]
Yes, they're basically just running a code analyzer; this is all automatic. They didn't find a single bug and I can't really say the code is better now...

**Comment by belaban** [comment]
Run FindBugs or IDEA Analyze and you get the same results...

**Pull request merged**
