### PR TITLE
JGRP-1968: JGroups missing JBoss logging internationalization

### PR DESCRIPTION
**Pull request by rpelisse**
Externalizing a bunch more messages - done by a script, so some little fiddling may be required afterward, but most generation issue have been catched.

### CODE REVIEW

**Comment by belaban** [comment]
Applied, with changes

**Comment by belaban** [comment]
Oh man, do I hate this crap ! I really don't believe in internationalization of error messages...
The automatic replacement leads to stupid things like this:
```
log.error(Util.getMessage("RequestOfType") + req.type + 
                                " sent an object of " + objectToRun + " which is invalid");
```
Because we're only internationalizing the first part, we could have an error message whose first part is French and the rest English...
Do you want to fix this manually ?
Using a resource bundle can lead to runtime exceptions if arguments are supplied incorrectly to resource error strings.

**Comment by rpelisse** [comment]
Yes, I'll work on that tomorrow, and do an other PR to remove this sort of i18n messages.

**Comment by rpelisse** [comment]
Hi Bela,

Would it not make more sense to turn this kind of message to accept parameter, like this one:

```java
JGRP000034: %s: failure sending message to %s: %s
```

This way will avoid the scenario where a message is "half translated" (and it will be more of an enhancement). I'm going to do that this afternoon and send a PR, but let me know if you don't to change the message like that....

**Comment by belaban** [comment]
No, that's exactly what I want and what I was referring to in my earlier comment.

**Pull request closed without merging**
