### PR TITLE
JGRP-2242 Narrow set of thrown exceptions in Streamable and Marshaller method signatures.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/JGRP-2242

Now that 4.0.x was branched, perhaps this is ready for inclusion?

### CODE REVIEW

**Comment by belaban** [comment]
What's the rationale again for changing almost all of JGroups? :-)

**Comment by pferraro** [comment]
@belaban This removes the need for consumers of these methods to consistently handle a non-specific java.lang.Exception - particularly useful when adapting to other marshalling frameworks.

**Comment by belaban** [comment]
Do you have an example (code)?

**Comment by pferraro** [comment]
Off the top of my head:
https://github.com/wildfly/wildfly/blob/master/clustering/server/src/main/java/org/wildfly/clustering/server/group/AddressSerializer.java#L49
https://github.com/wildfly/wildfly/blob/master/clustering/server/src/main/java/org/wildfly/clustering/server/group/AddressSerializer.java#L61
https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsAddress.java#L69
https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsAddress.java#L78
https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTopologyAwareAddress.java#L131
https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTopologyAwareAddress.java#L140

**Comment by belaban** [comment]
Hmm... so your code throws an IOException... But [1] is inconsistent: it throw IOException on write() and also on read(), but other code throws {{IOException, ClassNotFoundException}} on read().

I'll think about this

[1] https://github.com/wildfly/wildfly/blob/master/clustering/server/src/main/java/org/wildfly/clustering/server/group/AddressSerializer.java#L60

**Comment by pferraro** [comment]
These are pretty standard exception types to throw when reading/writing to/from an java.io.ObjectInput/ObjectOutut stream. See:
https://docs.oracle.com/javase/8/docs/api/java/io/Externalizable.html
https://github.com/wildfly/wildfly/blob/master/clustering/marshalling/api/src/main/java/org/wildfly/clustering/marshalling/Externalizer.java
https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/marshall/Externalizer.java
https://github.com/jboss-remoting/jboss-marshalling/blob/master/api/src/main/java/org/jboss/marshalling/Externalizer.java

This is because ObjectInput.readObject() itself throws both an IOException *or* a ClassNotFoundException, if the class descriptor from the stream cannot be loaded.
https://docs.oracle.com/javase/8/docs/api/java/io/ObjectInput.html#readObject--
Whereas ObjectOutput.writeObject(...) only ever throws an IOException (i.e. it cannot be the case that the class was not found, if we already have an instance of the class)
https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutput.html#writeObject-java.lang.Object-

**Comment by belaban** [comment]
OK, so both methods will only throw an IOException.
I'll change this in 4.1.0

**Comment by belaban** [comment]
I'll take a look, too. I'm currently busy with the port to Quarkus, but will take a look early next week.

**Comment by belaban** [comment]
I don't like having to add a {{ClassNoutFoundException}} to the readXXX() methods. As in your examples above, I'd like to add this exception only to methods (e.g. {{Util.readAddress()}}) that possibly load classes.
Adding this to {{Streamable.readFrom()}} is not desired.
WDYT?

**Comment by belaban** [comment]
> These are pretty standard exception types to throw when reading/writing to/from an java.io.ObjectInput/ObjectOutut stream. See:
> https://docs.oracle.com/javase/8/docs/api/java/io/Externalizable.html
> https://github.com/wildfly/wildfly/blob/master/clustering/marshalling/api/src/main/java/org/wildfly/clustering/marshalling/Externalizer.java
> https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/marshall/Externalizer.java
> https://github.com/jboss-remoting/jboss-marshalling/blob/master/api/src/main/java/org/jboss/marshalling/Externalizer.java
> 
> This is because ObjectInput.readObject() itself throws both an IOException _or_ a ClassNotFoundException, if the class descriptor from the stream cannot be loaded.
> https://docs.oracle.com/javase/8/docs/api/java/io/ObjectInput.html#readObject--
> Whereas ObjectOutput.writeObject(...) only ever throws an IOException (i.e. it cannot be the case that the class was not found, if we already have an instance of the class)
> https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutput.html#writeObject-java.lang.Object-

While that is correct, in most cases, JGroups does _not_ read/write Objects, but simply - primitive - types.

**Comment by pferraro** [comment]
> I'd like to add this exception only to methods (e.g. Util.readAddress()) that possibly load classes.

That would be a welcome improvement.

**Comment by belaban** [comment]
OK. I'll accept your PR, but will make additional modifications, as not all methods (e.g. in Util) have the correct exceptions.

**Comment by belaban** [comment]
Pushed to master. Let me know if this works for you

**Comment by pferraro** [comment]
That works. Thanks!

**Pull request closed without merging**
